
--1.INTERSECT
 
SELECT CART_ID
 FROM CART_PRODUCTS
 WHERE NAME = '우유'
 INTERSECT
 SELECT CART_ID
 FROM CART_PRODUCTS
 WHERE NAME = '요거트'


--우유가 속하는 것들의 아이디 중 요거트가 있는 것 구하기
SELECT DISTINCT(B.CART_ID)
FROM CART_PRODUCTS B
WHERE B.CART_ID IN (
    SELECT A.CART_ID
    FROM CART_PRODUCTS A
    WHERE A.NAME ='우유'
    )
AND  B.NAME ='요거트'
ORDER BY B.CART_ID